因子组成: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其使用的因子中，量价类因子和基本面类因子的占比是多少。注意，只说量价类因子占比多少
  和基本面因子占比多少。

  下面是范例:
  核心基金经理施恩2020年形成了较为完善的策略框架，近两年主要进行一些因子方面的优化调整。目前仍然是中低频量价因子为核心，占比80%以上，基本面和另类因子
  大约15%。未来优化方向仍然以各领域的因子挖掘为主，逐步丰富基本面、另类、高频量价因子。子策略层面也主要是核心基金经理施恩过往开发积累的，负责组合优化
  的研究员主要根据基金经理指示做一些细化的研究工作。 因子层面偏好人工挖掘，对因子的逻辑性有较高要求，机器学习挖掘的因子在5%以内，通常会使用10年以上数
  据做观测，对近2-3年数据给予更高的权重，每个月都在持续更迭因子，无具体比例统计，入库因子大约1000个，实盘使用500个左右，因子组合以非线性为主，实盘
  上线了9个子策略模型，暂未使用深度的机器学习。子策略模型信号融合后生产个股截面打分，模型暂未使用半小时以内的预测，日间alpha的贡献较为突出，以3-5天
  频段为主。2023年新招募了1名研究员负责高频因子挖掘，新的因子和策略大约需要3个月的测试，然后进行小规模实盘，每月进行微幅的因子调整。 选股范围为全市
  场个股，剔除一些ST股、财务方面有重大风险的、流动性较差的新股等，风险约束方面，由于是空气指增，并未针对特定指数做一些跟踪，主要限制单一个股持仓上限
  0.5%，平均持仓个股600个左右，单一行业从实盘运行情况来看，不超过20%，通过个股分散的限制，产品不会在行业、概念题材中过度暴露。交易信号在全天分布，
  年双边换手率70倍左右，并未集中在早盘，策略对交易系统的要求是特别高，交易算法主要使用第三方算法服务商，如卡方。 
  根据该段的描述，回答应该为：量价类因子：80%; 基本面因子：15%

  接下来，请对下述文本进行总结：
  xxxxxx

  注意，必须严格按照该格式输出：量价类因子：X%; 基本面因子：X%
  
模型种类: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其使用模型或组合中，判断其有没有使用机器学习，若有，则回答"非线性",若无，则回答"线性"
  注意，若管理人既用了机器学习模型，又用了线性模型，回答“线性+非线性”，注意，回答仅能是“线性”, “非线性”或 “线性+非线性”
  
  下面是范例：
  中性和指增多头端使用同一套选股模型，中性空头端根据500/1000多头端使用IC/IM，不留风险敞口。融券多空多头端也相同，但是用融券进行对冲。500/1000 指
  增选股模型相同，仅风格约束上有区别。
  多头端上，500和1000指增多头端，目前因子库数量400+因子，实盘中会使用的因子300个左右。70%为量价因子，剩余30%为基本面，分析师预期，以及新闻公告舆
  情，某品牌线上销售额等另类数据。量价类因子的数据频率有分钟，日，周，两周四个不同的频率。因子70%为手工挖掘，30%为机器学习合成的因子。组合上主要使用
  机器学习，优化函数的逻辑是给定一个可接受的最大回撤3%，在此基础上以最大夏普对组合进行约束。模型会根据四个不同频率的量价信号叠加基本面信息和另类因子
  ，综合择出200-300只预期收益较高的个股进行持有，个股上限不超过2%，barra控制0.5个标准差以内，还会控制与对标指数的相关性，不能低于0.85。因子模型
  迭代上，以月频迭代为主，会主要参考因子相关性和新因子对组合的边际收益率贡献。
  可转债套利主要做折溢价套利和折价转股套利。具体来说，在折溢价套利中，若某只可转债的价格与正股价格存在明显偏差，投资者同时购买可转债并卖空对应正股，
  以锁定并获利于二者价格差。而在折价转股套利中，当可转债转换为正股的成本明显低于正股当前的市场价格时，投资者会选择行使转股权利，随即将新获得的正股卖
  出，赚取转股价与市场价之间的价差。目前主要为统计套，转债估值方法未透露，但除了估值模型，也分析对应正股基本面，流动性边际变化等。发现套利机会后一般
  最多持有7个套利对，单套利对仓位占比不超过15%。目前非主推策略。
  
  根据该段描述，回答应该为：非线性。原因是"组合上主要使用机器学习"这句话
  
  下面是另一个范例：
  在因子组合上，管理人会参考因子相关性和因子收益率曲线，把相关性高或收益率相似的因子进行线性合成，同时主观控制每一个大类的因子的权重。目前经过合成后的
  大类因子不到 100 个，因子的权重上接近等权。策略迭代上面，管理人表示这套模型从2010年开始开发，已经经过了市场的验证，因子上以小修小补为主，不会进行
  大改。现在唯一感觉到危机的则是机器学习的广泛使用会对这套模型产生影响。因此现在也在逐渐探索机器学习的模型在现有因子上的应用。
  
  根据该段描述，回答应该为：线性。原因是"管理人会参考因子相关性和因子收益率曲线，把相关性高或收益率相似的因子进行线性合成"这句话
  
  接下来，请对以下文本进行总结：
  xxxxxx
  
  注意，必须严格按照该格式输出：只能回答“线性”, “非线性”或 “线性+非线性”

策略类型: |
  文本总结任务：将一段描述某量化私募的简介文本进行总结，其中包括成立时间，管理规模，目前策略等。你的目标是找到其使用的策略，
  记住，出现“指增”或类似字样的为指数增强；出现“中性”或类似字样的为市场中性；出现“CTA”相关字样的为量化CTA
  你可以选择输出的策略有：“量化CTA”, “指数增强”, “市场中性”, “股票多空”,"量化多头","未知"中的一个或多个
  
  下面是范例:
  上海泓赫投资管理有限公司，成立于 2016年 04 月 11 日， 2019年 10 月 31 日在协会备案。为协会观察会员，目前管理规模3亿。3000 万为量
  化多头，剩余的为纯债策略与少部分量化多头+纯债的复合策略，以及少量的自营主观多头策略
  
  根据该段描述，回答应为"量化多头"，虽然后面还有描述别的策略的，但若与我给你的选项匹配不上，则不用管它。
  
  下面是另一个范例：
  上海象上私募基金管理有限公司，成立于 2021年 07 月 27 日， 2022年 01 月 11 日在协会备案。非协会会员，目前管理2亿。不到 500 万为自
  营的主观多头产品，剩下30%为股票市场中性策略，70%为中证500指增
  根据该段描述，回答应为"“市场中性”和“指数增强”"。因为这句话“剩下30%为股票市场中性策略，70%为中证500指增”，“指增”是指数增强的缩写
  
  注意，必须严格按照格式输出，只能输出“量化CTA”, “指数增强”, “市场中性”, “股票多空”,"量化多头", "未知" 中的一个或多个
