因子组成: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其使用的因子中，量价类因子和基本面类因子的占比是多少。注意，只说量价类因子占比多少
  和基本面因子占比多少。


  接下来，请对下述文本进行总结：
  xxxxxx
  
  注意且量价类因子+基本面因子之和不能超过100%
  注意，必须严格按照该格式输出：量价类因子：X%; 基本面因子：X%。X除数字外不能出现其他字符, 不允许出现模糊范围，如量价类因子：70-80%
  

因子挖掘: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其使用的因子中，是否主要是机器学习挖掘的。若是，则输出"机器学习",若不算，则输出
  "手工挖掘"
  接下来，请对下述文本进行总结：
  xxxxxx
  
  注意，必须严格按照格式输出，只能输出 "机器学习" 或 "手工挖掘"

模型种类: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其使用模型或组合中，机器学习是否是其策略的重要组成部分，若有，则回答"非线性",若无，则回答"线性"
  注意，回答仅能是“线性”, “非线性”或 “线性+非线性”
  
  接下来，请对以下文本进行总结：
  xxxxxx
  
  注意，必须严格按照该格式输出：只能回答“线性”, “非线性”

策略类型: |
  文本总结任务：将一段描述某量化私募的简介文本进行总结，其中包括成立时间，管理规模，目前策略等。你的目标是找到其使用的策略，
  记住，出现“指增”或类似字样的为指数增强；出现“中性”或类似字样的为市场中性；出现“CTA”相关字样的为量化CTA
  你可以选择输出的策略有：“量化CTA”, “指数增强”, “市场中性”, “股票多空”,"量化多头","未知"中的一个或多个
  
  下面是范例:
  上海泓赫投资管理有限公司，成立于 2016年 04 月 11 日， 2019年 10 月 31 日在协会备案。为协会观察会员，目前管理规模3亿。3000 万为量
  化多头，剩余的为纯债策略与少部分量化多头+纯债的复合策略，以及少量的自营主观多头策略
  
  根据该段描述，回答应为"量化多头"，虽然后面还有描述别的策略的，但若与我给你的选项匹配不上，则不用管它。
  
  下面是另一个范例：
  上海象上私募基金管理有限公司，成立于 2021年 07 月 27 日， 2022年 01 月 11 日在协会备案。非协会会员，目前管理2亿。不到 500 万为自
  营的主观多头产品，剩下30%为股票市场中性策略，70%为中证500指增
  根据该段描述，回答应为"“市场中性”和“指数增强”"。因为这句话“剩下30%为股票市场中性策略，70%为中证500指增”，“指增”是指数增强的缩写
  
  注意，必须严格按照格式输出，只能输出“量化CTA”, “指数增强”, “市场中性”, “股票多空”,"量化多头", "未知" 中的一个或多个

选股范围: |
  文本总结任务：将一段描述某量化私募的配置逻辑的文本进行总结，找到其选股范围，若是在指数内选股，则输出“指数内选股”，若全市场选股，则输出“全市场选股”,
  ，如果没有明确写到为指数内选股，则都认为是“全市场选股”，若有明确写到“全市场选股”，则就是“全市场选股”
  
  接下来，请对下述文本进行总结：
  xxxxxx
  注意，必须严格按照该格式输出：只能输出“指数内选股”和“全市场选股”
  

交易频率: |
  文本总结任务，将一段描述量化私募的持仓特征的文本进行总结，找到其股票策略（包括量化选股，量化多头，指增，中性）的换手率，不要把叠加T0后的换手率
  算进去，若找到不止一个换手率，则只输出最大的换手率，并对其换手率进行判断：

  
  接下来，请对下述文本进行总结：
  xxxxxx
  注意，必须严格按照该格式输出: 换手率X倍，X除数字外不能出现其他字符

持股数量: |
  文本总结任务，将一段描述量化私募的